version: '3.9'
services:
  pg:
    image: postgres:16
    environment:
      POSTGRES_USER: analyst
      POSTGRES_PASSWORD: analyst
      POSTGRES_DB: sales
    ports: ["5432:5432"]
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/seeds:/seeds
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports: ["8080:8080"]
volumes:
  pgdata:
